# Generated by Django 3.2.2 on 2021-05-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rubro', models.CharField(blank=True, choices=[('1', 'Rubro1'), ('2', 'Rubro2'), ('3', 'Rubro3')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('profesion', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejemplo.empresa')),
            ],
        ),
    ]
