# Generated by Django 3.2.2 on 2021-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('prevision_social', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('numero_telefono', models.CharField(max_length=50)),
                ('sexo_paciente', models.CharField(choices=[('1', 'Hombre'), ('2', 'Mujer')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
