# Generated by Django 3.2.2 on 2021-05-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_auto_20210523_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut_contacto', models.CharField(max_length=50)),
                ('rutCont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplo.paciente')),
            ],
        ),
    ]
