# Generated by Django 3.2.2 on 2021-05-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_contacto_respaldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_telefono_contacto', models.CharField(max_length=50)),
                ('parentezco', models.CharField(max_length=50)),
                ('rut_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplo.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad_profesional', models.CharField(choices=[('1', 'Médico General'), ('2', 'Enfermera'), ('3', 'Nutricionista'), ('4', 'Fonoaudiologo'), ('5', 'Psicologo'), ('6', 'Kinesiologo'), ('7', 'Trabajor Social'), ('8', 'Teraupetica Ocupacional'), ('9', 'Tecnico Paramedico')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto_respaldo',
        ),
    ]
