# Generated by Django 3.2.2 on 2021-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0004_auto_20210523_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(choices=[('1', 'Orientacion'), ('2', 'Salud Mental'), ('3', 'Red Odontologica'), ('4', 'Red Oncologica'), ('5', 'Quimicos Farmaceuticos'), ('6', 'Red Imagenologia'), ('7', 'Red ITS'), ('8', 'Red Medicina Nuclear'), ('9', 'Red Telemedicina'), ('10', 'Red Salud Sexual')], max_length=50)),
            ],
        ),
    ]
