# Generated by Django 3.2.2 on 2021-05-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0005_programas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidadprofesional', models.CharField(choices=[('1', 'Médico General'), ('2', 'Enfermera'), ('3', 'Nutricionista'), ('4', 'Fonoaudiologo'), ('5', 'Psicologo'), ('6', 'Kinesiologo'), ('7', 'Trabajor Social'), ('8', 'Teraupetica Ocupacional'), ('9', 'Tecnico Paramedico')], max_length=50)),
                ('programa', models.CharField(choices=[('1', 'Orientacion'), ('2', 'Salud Mental'), ('3', 'Red Odontologica'), ('4', 'Red Oncologica'), ('5', 'Quimicos Farmaceuticos'), ('6', 'Red Imagenologia'), ('7', 'Red ITS'), ('8', 'Red Medicina Nuclear'), ('9', 'Red Telemedicina'), ('10', 'Red Salud Sexual')], max_length=50)),
                ('nombre_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplo.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='Programas',
        ),
    ]
