# Generated by Django 3.2.2 on 2021-05-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0006_auto_20210523_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_responsable', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=12)),
                ('contraseña', models.CharField(max_length=12)),
                ('programas_asignados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplo.paciente')),
            ],
        ),
    ]
