# Generated by Django 3.2.2 on 2021-05-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0007_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(choices=[('1', 'CESFAM LAS COMPAÑIAS'), ('2', 'EMILIO SCHAFFHAUSER')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
