# Generated by Django 3.2.2 on 2021-05-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0008_auto_20210523_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
