# Generated by Django 3.2.2 on 2021-05-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0009_delete_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('cita_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplo.paciente')),
            ],
        ),
    ]
